source.. = src/
bin.includes = .,\
               META-INF/,\
               plugin.xml,\
               syntaxes/,\
               lib/sheepdogasciidoc.jar,\
               lib/sheep-dog-grammar.jar
