name: Publish Sheep Dog IDE Release

on:
  workflow_dispatch:
concurrency:
  group: sheep-dog-ide
  cancel-in-progress: false
permissions:
  contents: write
  packages: write

jobs:
  sheepdogeclipseplugin-parent:
    uses: farhan5248/sheep-dog-ops/.github/workflows/release-maven.yml@main
    with:
      project: 'sheepdogeclipseplugin.parent'
    secrets: inherit
